# Generated by Django 6.0.3 on 2026-03-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_description', models.TextField()),
                ('registration_close_date', models.DateField()),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
